import { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { createServerSupabaseClient, SITE_URL } from '@/lib/supabase'
import type { Wallpaper } from '@/types'

export const metadata: Metadata = {
  title: 'AI Wallpapers — Free AI Generated Backgrounds 2026',
  description: 'Download stunning AI generated wallpapers for free. Unique AI art backgrounds created with Stable Diffusion, Midjourney and DALL-E. HD and 4K quality. Updated daily.',
  keywords: ['AI wallpapers', 'AI generated wallpapers', 'artificial intelligence wallpapers', 'Midjourney wallpapers', 'Stable Diffusion wallpapers', 'AI art backgrounds'],
  alternates: { canonical: `${SITE_URL}/ai-wallpapers` },
  openGraph: {
    title: 'AI Wallpapers — Free AI Generated Backgrounds 2026',
    description: 'Unique AI art backgrounds created with Stable Diffusion, Midjourney and DALL-E.',
    url: `${SITE_URL}/ai-wallpapers`,
  },
}

export const revalidate = 600

const aiStyles = [
  { name: 'AI Abstract', icon: '🎨', description: 'Futuristic abstract art' },
  { name: 'AI Nature', icon: '🌿', description: 'AI-generated landscapes' },
  { name: 'AI Space', icon: '🌌', description: 'Cosmic AI imagery' },
  { name: 'AI Cyberpunk', icon: '🌃', description: 'Neon-lit cityscapes' },
  { name: 'AI Fantasy', icon: '🧙', description: 'Magical AI worlds' },
  { name: 'AI Minimal', icon: '⚪', description: 'Clean AI designs' },
]

const aiFeatures = [
  { icon: '🤖', title: 'Advanced AI Models', description: 'Generated with Stable Diffusion, Midjourney and DALL-E 3' },
  { icon: '✨', title: 'Unique Artwork', description: 'Every wallpaper is one-of-a-kind — no duplicates' },
  { icon: '📐', title: '4K Resolution', description: 'Ultra-high quality AI art optimized for all screens' },
  { icon: '🔄', title: 'Daily Generation', description: 'New AI wallpapers added every single day' },
]

export default async function AIWallpapersPage() {
  const supabase = createServerSupabaseClient()

  // Fetch AI category wallpapers — or fallback to all
  const { data: categoryData } = await supabase
    .from('categories')
    .select('id')
    .ilike('name', '%ai%')
    .limit(1)
    .maybeSingle()

  let wallpapers: Wallpaper[] = []

  if (categoryData?.id) {
    const { data } = await supabase
      .from('wallpapers')
      .select('id, title, slug, thumbnail_url, download_count, is_premium')
      .eq('is_active', true)
      .eq('category_id', categoryData.id)
      .order('download_count', { ascending: false })
      .limit(48)
    wallpapers = (data || []) as Wallpaper[]
  }

  // Fallback to all wallpapers if AI category not found
  if (wallpapers.length === 0) {
    const { data } = await supabase
      .from('wallpapers')
      .select('id, title, slug, thumbnail_url, download_count, is_premium')
      .eq('is_active', true)
      .order('download_count', { ascending: false })
      .limit(48)
    wallpapers = (data || []) as Wallpaper[]
  }

  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: 'AI Generated Wallpapers',
    description: 'Free AI generated wallpapers created with Stable Diffusion and Midjourney',
    url: `${SITE_URL}/ai-wallpapers`,
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />

      {/* Hero */}
      <div className="relative bg-gradient-to-br from-violet-900/40 via-gray-900 to-blue-900/30 py-16 px-4 border-b border-gray-800 overflow-hidden">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top_right,_var(--tw-gradient-stops))] from-violet-600/10 via-transparent to-transparent pointer-events-none" />
        <div className="max-w-7xl mx-auto text-center relative">
          <span className="inline-block bg-violet-700/30 text-violet-300 text-sm px-4 py-1.5 rounded-full mb-4 border border-violet-700/50">
            🤖 AI Generated
          </span>
          <h1 className="text-4xl md:text-5xl font-bold text-white mb-4">AI Wallpapers</h1>
          <p className="text-gray-400 text-lg max-w-2xl mx-auto leading-relaxed mb-8">
            Stunning, unique wallpapers generated by artificial intelligence. Created with
            Stable Diffusion, Midjourney and DALL-E — every image is one of a kind.
          </p>
          <div className="flex flex-wrap gap-3 justify-center">
            <Link href="/wallpapers" className="bg-violet-700 hover:bg-violet-600 text-white px-6 py-3 rounded-lg font-medium transition-colors">
              Browse All Wallpapers
            </Link>
            <Link href="/categories" className="bg-gray-800 hover:bg-gray-700 text-white px-6 py-3 rounded-lg font-medium transition-colors">
              View Categories
            </Link>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 py-10">

        {/* AI Features */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4 mb-12">
          {aiFeatures.map((f) => (
            <div key={f.title} className="bg-gray-800/60 rounded-xl p-5 border border-gray-700 text-center">
              <div className="text-3xl mb-3">{f.icon}</div>
              <h3 className="text-white font-medium text-sm mb-1">{f.title}</h3>
              <p className="text-gray-500 text-xs leading-relaxed">{f.description}</p>
            </div>
          ))}
        </div>

        {/* AI Styles */}
        <div className="mb-10">
          <h2 className="text-xl font-semibold text-white mb-5">AI Styles</h2>
          <div className="grid grid-cols-3 md:grid-cols-6 gap-3">
            {aiStyles.map((style) => (
              <div key={style.name} className="bg-gradient-to-br from-violet-900/30 to-blue-900/30 border border-violet-700/30 rounded-xl p-4 text-center hover:border-violet-500/50 transition-colors cursor-pointer">
                <div className="text-2xl mb-2">{style.icon}</div>
                <p className="text-white text-xs font-medium">{style.name}</p>
                <p className="text-gray-500 text-xs mt-0.5">{style.description}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Wallpapers grid */}
        <div className="flex items-center justify-between mb-6">
          <h2 className="text-xl font-semibold text-white">AI Generated Wallpapers</h2>
          <span className="text-gray-400 text-sm">{wallpapers.length} wallpapers</span>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-3">
          {wallpapers.map((w) => (
            <Link
              key={w.id}
              href={`/wallpaper/${w.slug}`}
              className="group relative rounded-lg overflow-hidden bg-gray-800 aspect-[9/16] block"
            >
              {w.thumbnail_url && (
                <Image
                  src={w.thumbnail_url}
                  alt={w.title}
                  fill
                  sizes="(max-width: 640px) 50vw, 16vw"
                  unoptimized
                  className="object-cover group-hover:scale-105 transition-transform duration-300"
                />
              )}
              <div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
              <p className="absolute bottom-2 left-2 right-2 text-white text-xs font-medium line-clamp-2 opacity-0 group-hover:opacity-100 transition-opacity">
                {w.title}
              </p>
            </Link>
          ))}
        </div>
      </div>
    </>
  )
}
