-- =============================================================================
-- VERIFICARE: Care tabele au date vs sunt goale (tabele moarte din proiecte vechi)
-- Rulează în SQL Editor — poate dura 5-10 secunde
-- =============================================================================

SELECT
  tablename,
  (xpath('/row/c/text()',
    query_to_xml('SELECT COUNT(*) AS c FROM public.' || quote_ident(tablename), false, true, '')
  ))[1]::text::int AS row_count
FROM pg_tables
WHERE schemaname = 'public'
  AND tablename IN (
    -- Tabele cu policies DAR nefolosite în frontend — de verificat
    'ad_config',
    'ad_settings',
    'admin_actions_log',
    'admin_dashboard_stats',
    'admin_logs',
    'admin_notifications',
    'admin_roles',
    'admin_settings',
    'admin_users',
    'app_settings',
    'audit_logs',
    'bfw_plans',
    'bfw_subscriptions',
    'cache_invalidations',
    'cascade_audit_log',
    'content_freshness',
    'cta_button_settings',
    'daily_quotas',
    'download_attempts',
    'download_links',
    'download_logs',
    'download_rate_limits',
    'download_sessions',
    'downloads',
    'events',
    'homepage_content',
    'homepage_content_history',
    'image_security_metadata',
    'internal_links',
    'media_files',
    'media_items',
    'media_uploads',
    'notification_settings',
    'notifications',
    'order_items',
    'order_status_logs',
    'orders',
    'payments',
    'performance_logs',
    'plans',
    'premium_banner_audit_log',
    'premium_membership_requests',
    'premium_memberships',
    'premium_orders',
    'premium_plans',
    'premium_purchase_requests',
    'premium_requests',
    'promotional_offers',
    'purchase_requests',
    'rate_limit_config',
    'redirects',
    'related_wallpapers',
    'ringtone_downloads',
    'search_analytics',
    'search_suggestions',
    'security_logs',
    'settings',
    'site_branding',
    'site_settings',
    'site_texts',
    'slug_redirects',
    'stripe_customers',
    'structured_data',
    'subscriptions',
    'trending_searches',
    'used_tokens',
    'user_subscriptions',
    'users',
    'wallpaper_collections',
    'wallpaper_downloads',
    'wallpaper_plans',
    'wallpaper_tags',
    'wallpapers_categories'
  )
ORDER BY row_count DESC, tablename;
